dominiolifetagGen/TagLifeASPMVC/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace TagLifeASPMVC.Models
{
    public class Usuario
    {

        [ScaffoldColumn(false)]
        public int ID {get;set;}
        public string Nombre {get;set;}
        public string Email { get; set; }
        public string Password { get; set; }
        public string Pais { get; set; }
        public int Telefono { get; set; }
        public string Nickname { get; set; }
        public string Fotoruta { get; set; }
        public bool Activacion { get; set; }
        public string Listamegusta { get; set; }
        public string Categoriassuscrito { get; set; }
        public bool Bloqueado { get; set; }
    }
    //modelo que nos servira para recorger los datos del login, uno de los dos estara vacio por defecto el email
    public class LoginModelS
    {
        [Required]
        public string Nick { get; set; }
  
        [Required]
        [DataType(DataType.Password)]
        public string Pass { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email{ get; set; }
    }
}

dominiolifetagGen/TagLifeASPMVC/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DominiolifetagGenNHibernate.CAD.Dominiolifetag;
using DominiolifetagGenNHibernate.EN.Dominiolifetag;
using TagLifeASPMVC.Models;

namespace TagLifeASPMVC.Controllers
{
    public class CategoriaController : Controller
    {
        //
        // GET: /Categoria/

        public ActionResult Index()
        {
            CategoriaCAD cad = new CategoriaCAD();
            IList<CategoriaEN> lista = cad.ReadAllDefault(0, -1);
            IEnumerable<Categoria> listEN = new CategoriaAssembler().ConvertListENToModel(lista).ToList();
            return RedirectToAction("Listar");
        }

        public ActionResult CargarCategorias()
        {
            CategoriaCAD cad = new CategoriaCAD();
            IList<CategoriaEN> lista = cad.ReadAllDefault(0, 0);
            IEnumerable<Categoria> listEN = new CategoriaAssembler().ConvertListENToModel(lista).ToList();
            return PartialView(listEN);
        }

        public ActionResult categorias()
        {
            CategoriaCAD cad = new CategoriaCAD();
            //que empieze por la categoria 1 y saque 6
            IList<CategoriaEN> lista = cad.ListadoCategorias(1, 6);
            ViewData["listas"] = lista;
            return View();
        }

        public ActionResult CategoriaList()
        {
            return View();
        }
        //
        // GET: /Categoria/Details/5

        [HttpPost]
        [AllowAnonymous]
        public ActionResult CrearCategoria(String nombre, String descripcion, String edad)
        {
            CategoriaCAD cen = new CategoriaCAD();
            CategoriaEN us = new CategoriaEN();
            if (Session["idadmin"] != null || (String)Session["idadmin"] != "")
            {                
                us.Nombre = nombre;
                us.Descripcion = descripcion;
                us.Edad = Convert.ToInt32(edad);

            }
            int use = cen.New_(us);

            if (use != -1)
            {               
                String mensaje2 = "categoria creada";
                return RedirectToAction("categorias", "Administrador", new { men = mensaje2 });
            }
        
            String mensaje = "categoria incorrecta";

            return RedirectToAction("categorias", "Administrador", new { men = mensaje });
        }

		
		[HttpPost]
        [AllowAnonymous]
        public ActionResult BorrarCategoria(int dato)
        {
            CategoriaCAD cen = new CategoriaCAD();
            CategoriaEN us = new CategoriaEN();
            if (Session["idadmin"] != null || (String)Session["idadmin"] != "")
            {
                //no se si falta convertir de alguna forma dato para usarlo
                cen.Destroy(dato);
                String mensaje2 = "categoria eliminada";
                return RedirectToAction("Categorias", "Publicacion", new { men = mensaje2 });
            }
        
            String mensaje = "error";

            return RedirectToAction("Categorias", "Publicacion", new { men = mensaje });
        }
		
            public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Categoria/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Categoria/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Categoria/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Categoria/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Categoria/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Categoria/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

dominiolifetagGen/TagLifeASPMVC/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DominiolifetagGenNHibernate.CAD.Dominiolifetag;
using DominiolifetagGenNHibernate.CEN.Dominiolifetag;
using DominiolifetagGenNHibernate.EN.Dominiolifetag;
using TagLifeASPMVC.Models;
using System.Diagnostics;
using System.Text;
using System.IO;

namespace TagLifeASPMVC.Controllers
{
    public class UsuarioController : Controller
    {
        //
        // GET: /Usuario/

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Close()
        {
            Session["iduser"] = null;
            return RedirectToAction("Index", "Usuario", new { men = "close" });
        }

        public ActionResult perfil()
        {

            UsuarioCAD cen = new UsuarioCAD();
            UsuarioEN usr;
            UsuarioCEN usuarioCEN = new UsuarioCEN();

            if (Session["iduser"] != null)
            {
                usr = cen.ReadOIDDefault(int.Parse((String)Session["iduser"]));
                if (usr != null)
                {
                    ViewBag.name = usr.Nombre;
                    ViewBag.phone = usr.Telefono;
                    ViewBag.email = usr.Email;
                    ViewBag.avatar = usr.Fotoruta;
                }
            }
            return View();
        }

        public ActionResult MisPublicaciones()
        {
            return View();
        }

        public ActionResult Reportar(int idpu)
        {
            ReporteCEN repor = new ReporteCEN();
            try
            {
                repor.New_(DateTime.Now, false, idpu);
            }
            catch (Exception e)
            {
                //no se hace nada
            }
            return RedirectToAction("Index","Publicacion", new {idpublicacion = idpu});
        }
        public ActionResult Like(int idpu)
        {
            UsuarioCAD cen = new UsuarioCAD();
            PublicacionCAD cad = new PublicacionCAD();
            UsuarioEN usr;


            if (Session["iduser"] != null)
            {
                usr = cen.ReadOIDDefault(int.Parse((String)Session["iduser"]));
                if (usr != null)
                {
                    if (usr.Listamegusta == "")
                    {
                        usr.Listamegusta = Convert.ToString(idpu);
                    }
                    else
                    {
                        String[] publis = usr.Listamegusta.Split(',');
                        if (!usr.Listamegusta.Contains(','))
                        {
                            if (!(Convert.ToString(idpu) == usr.Listamegusta))
                            {
                                usr.Listamegusta = usr.Listamegusta + "," + Convert.ToString(idpu);
                            }
                        }
                        else
                        {
                            Boolean existe = false;
                            foreach (string publica in publis)
                            {
                                if (existe == false && publica == Convert.ToString(idpu))
                                {
                                    existe = true;
                                }
                            }
                            if (!existe)
                            {
                                usr.Listamegusta = usr.Listamegusta + "," + Convert.ToString(idpu);
                            }
                        }
                    }
                }
                
                cen.Modify(usr);
            }
            ViewBag.Men = "Correcto";
            return RedirectToAction("Index", "Publicacion", new { idpublicacion = idpu, Men = "Correcto" });
        }
        public ActionResult Publi()
        {
            PublicacionCAD publiCAD = new PublicacionCAD();
            IList<PublicacionEN> publicaciones = publiCAD.ReadAllDefault(0, 0);
            UsuarioCAD usuCAD = new UsuarioCAD();
            UsuarioEN usu;

            usu = usuCAD.ReadOIDDefault(int.Parse((String)Session["iduser"]));
            IList<PublicacionEN> publiUsu = new List<PublicacionEN>();
            foreach (PublicacionEN item in publicaciones)
            {
                if (item.Usuario.ID == usu.ID)
                {
                    publiUsu.Add(item);
                }
            }

            IEnumerable<Publicacion> ulpu = new PublicacionAssembler().ConvertListENToModel(publiUsu).ToList();
            return PartialView(ulpu);
        }
        public ActionResult AgregarCateg(int idCategoria)
        {
            UsuarioCAD cen = new UsuarioCAD();
            CategoriaCAD cad = new CategoriaCAD();
            UsuarioEN usr;

            
            if (Session["iduser"] != null)
            {
                usr = cen.ReadOIDDefault(int.Parse((String)Session["iduser"]));
                if (usr != null)
                {
                    if (usr.Categoriassuscrito == "")
                    {
                        usr.Categoriassuscrito = Convert.ToString(idCategoria);
                    }
                    else
                    {
                        String[] cates = usr.Categoriassuscrito.Split(',');
                        if (!usr.Categoriassuscrito.Contains(','))
                        {
                            if (!(Convert.ToString(idCategoria) == usr.Categoriassuscrito))
                            {
                                usr.Categoriassuscrito = usr.Categoriassuscrito + "," + Convert.ToString(idCategoria);
                            }
                        }
                        else
                        {
                            Boolean existe = false;
                            foreach (string catego in cates)
                            {
                                if (existe == false && catego == Convert.ToString(idCategoria))
                                {
                                    existe = true;
                                }
                            }
                            if (!existe)
                            {
                                usr.Categoriassuscrito = usr.Categoriassuscrito + "," + Convert.ToString(idCategoria);
                            }
                        }
                    }
                }
                cen.Modify(usr);
            }
            return RedirectToAction("Index", "Usuario");
        }
        public ActionResult favoritos()
        {
            return View();
        }

        public ActionResult Subircontenido(FormCollection scont)
        {
            if (scont["nombre"] != null && scont["tipo"] != null && scont["archivo"] != null && scont["categorias"] != null)
            {
                System.Diagnostics.Debug.WriteLine("nombre: " + scont["nombre"]);
                System.Diagnostics.Debug.WriteLine("tipo: " + scont["tipo"]);
                System.Diagnostics.Debug.WriteLine("archivo: " + scont["archivo"]);
                System.Diagnostics.Debug.WriteLine("iduser: " + Session["iduser"]);

                IList<EtiquetaEN> etil = new List<EtiquetaEN>();
                IList<int> catel = new List<int>();

                string[] cateq = scont["categorias"].Split(',');
                foreach (string item in cateq)
                {
                    catel.Add(int.Parse(item));
                    System.Diagnostics.Debug.WriteLine(item);
                }

                PublicacionCEN cen = new PublicacionCEN();
                int use = cen.New_(DateTime.Today, scont["nombre"], scont["tipo"], scont["archivo"], Convert.ToInt32(Session["iduser"]), etil, catel);

                //Etiquetas
                IList<int> lista = new List<int>();
                EtiquetaCEN etiCEN = new EtiquetaCEN();
                string[] etiq = scont["etiquetas"].Split(',');
                if (etiq.Length < 1)
                {
                    etiq = new String[1];
                    etiq[0] = etiq[0];
                }
                EtiquetaCAD cad = new EtiquetaCAD();
                IList<EtiquetaEN> etique = cad.ReadAllDefault(0, 0);

                PublicacionCAD publicad = new PublicacionCAD();
                IList<PublicacionEN> publien = publicad.ReadAllDefault(0, 0);

                lista.Add(use);
                bool existe = false;
                foreach (String item in etiq)
                {
                    foreach (EtiquetaEN item2 in etique)
                    {
                        if (item2.Nombre == item)
                        {
                            existe = true;
                            //Buscar publicacion
                            foreach (PublicacionEN item3 in publien)
                            {
                                if(item3.ID == use)
                                {
                                    //agregar a la lista la nueva publicacion
                                    System.Diagnostics.Debug.WriteLine("tengo etiqueta:"+item2.Nombre + " publi:" +item3.Nombre);
                                    //item2.Publicacion.Add(item3);
                                }
                            }
                        }
                    }
                    if (existe == false)
                    {
                        int etiqueta1 = etiCEN.New_(item, lista);
                        System.Diagnostics.Debug.WriteLine(item);
                    }
                    existe = false;
                }

                System.Diagnostics.Debug.WriteLine(use + " id devuelto");
                return RedirectToAction("Index", "Usuario");
            }
            return View();
        }


dominiolifetagGen/TagLifeASPMVC/Views/Usuario/About.cshtml
@{
    ViewBag.Title = "¿Quienes Somos?";
    Layout = "~/Views/Shared/_LayoutUSER.cshtml";
}

<div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
        <h3>¿Quienes Somos?</h3>
        <p>Esta idea nacio en un grupo de trabajo donde jovenes estudiantes y emprendedores les toco hacer un proyecto, en un principio ibamos a hacer una tienda online de hamburguesas congeladas y precocinadas a 360 º pero descartamos esta idea, para hacer una especie de red social basada en contenido multimedia y sabeis porque ?????? porque eramos futuros ingenieros multimedia en plena ola de ideas y pensemos porque no. </p>
        <p><b>Asi se hizo LifeTag</b></p>
    </div>
    <div class="col-sm-2"></div>
</div>

dominiolifetagGen/TagLifeASPMVC/Views/Usuario/Contact.cshtml
@{
    ViewBag.Title = "Contactanos";
    Layout = "~/Views/Shared/_LayoutUSER.cshtml";
}

<div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">
        <h3>Contactar:</h3>
        <p><b>Telefono de contacto: </b> +34966365365</p>
        <p><b>Email: </b><a href="mailto:lifetag@lifetag.com"> lifetag@lifetag.com</a></p>
        <p><b style="color:red;">Para cualquier problema con alguna publicacio presione el boton de reportar.</b></p>
        <p>Siguenos por las redes sociales:</p>
        <img src="/images/face.png" class="img-thumbnail"/>
        <img src="/images/twi.png" class="img-thumbnail" />
        <img src="/images/tele.png" class="img-thumbnail"/>
        <img src="/images/you.png" class="img-thumbnail"/>
    </div>
    <div class="col-sm-1"></div>
</div> 

dominiolifetagGen/TagLifeASPMVC/Views/Usuario/Index.cshtml
@model TagLifeASPMVC.Models.Usuario

@{
    ViewBag.Title = "Inicio  | Tablon";
    Layout = "~/Views/Shared/_LayoutUSER.cshtml";
}

<div class="container-fluid">
    <!--solo con container se ajusta mas-->
    <h1><kbd> Top Visitas </kbd></h1>
    <!----------------------------------------------CARRUSEL ----------------------------------------------------->
    <div class="col-sm-4">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
               @{Html.RenderAction("Carrussel1", "Publicacion");} 
                <!--
                <div class="item">
                    <img src="https://awol.junkee.com/wp-content/uploads/2017/07/3598596321_4cfde29fe7_o.jpg" alt="Chicago">
                    <div class="carousel-caption">
                        <h3>Auroras boreales en Islandia</h3>
                        <p>Espectáculo que nadie se debería perderse</p>
                    </div>
                </div>-->

            </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

    </div>

    <div class="col-sm-4">
        <div id="myCarousel2" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel2" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel2" data-slide-to="1"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                
                @{Html.RenderAction("Carrussel2", "Publicacion");}
                
            </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel2" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel2" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

    </div>

    <div class="col-sm-4">
        <div id="myCarousel3" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel3" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel3" data-slide-to="1"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                
                @{Html.RenderAction("Carrussel3", "Publicacion");}
                
            </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel3" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel3" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

    </div>
</div>


<h1><kbd> Categorias </kbd></h1>

    <ul class="nav nav-tabs">

        @{Html.RenderAction("CapaSeleccion", "Publicacion");}

    </ul>


dominiolifetagGen/TagLifeASPMVC/Views/Usuario/MisPublicaciones.cshtml
@model TagLifeASPMVC.Models.Usuario
@{
    ViewBag.Title = "Publicaciones";
    Layout = "~/Views/Shared/_LayoutUSER.cshtml";
}


<body>

    <div class="text-center">
        <span class="glyphicon glyphicon-user" style="font-size:100px;"></span>
    </div>

        <h1 class="text-center">@if(Model!=null){Html.Encode(Model.Nombre);}</h1>
        <h2 class="text-center"><kbd>Mis Publicaciones</kbd></h2>
    
        <div class="container">
            <div class="row">
                
                        @{Html.RenderAction("Publi", "Usuario");}
                    
            </div>
        </div>
</body>


dominiolifetagGen/TagLifeASPMVC/Views/Usuario/SearchAv.cshtml
@model IEnumerable<TagLifeASPMVC.Models.Publicacion>

@{
    ViewBag.Title = "Busqueda avanzada";
    Layout = "~/Views/Shared/_LayoutUSER.cshtml";
}

<h3>Resultados de la busqueda:</h3>
<br />
<a href="#" data-toggle="modal" data-target="#myModal">Busqueda Avanzada</a>
<br />

<div class="row">
    <div class="col-sm-12">
        @{
            if (Model != null)
            {
                foreach (var item in Model)
                {
                    //@:<img class="img-responsive" src="@Html.DisplayFor(modelItem => item.Archivo)" alt="@item.Nombre" style="width:25%"/>
                    @:<img src="@Html.DisplayFor(modelItem => item.Archivo)" class="img-thumbnail" alt="@item.Nombre" style="width:24%">
                }   
            }
        }
    </div>
</div>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Busqueda avanzada</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("SearchAv", "Usuario", FormMethod.Post))
                {
                    @:<input type="text" name="busqueda" class="form-control" placeholder="Escribe tu busqueda">
                    Html.RenderAction("CategoriaList", "Categoria");
                    @:<input type="submit" />
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

dominiolifetagGen/TagLifeASPMVC/Views/Usuario/SearchU.cshtml
@model IEnumerable<TagLifeASPMVC.Models.Publicacion>

@{
    ViewBag.Title = "Busqueda";
    Layout = "~/Views/Shared/_LayoutUSER.cshtml";
}

<h3>Resultados de la busqueda:</h3>
<br />
<a href="#" data-toggle="modal" data-target="#myModal">Busqueda Avanzada</a>
<br/>

<div class="row">
    <div class="col-sm-12">
        @{
            if (Model != null)
            {
                foreach (var item in Model)
                {
                    //@:<img class="img-responsive" src="@Html.DisplayFor(modelItem => item.Archivo)" alt="@item.Nombre" style="width:25%"/>
                    @:<img src="@Html.DisplayFor(modelItem => item.Archivo)" class="img-thumbnail" alt="@item.Nombre" style="width:24%">
            }
            }
        }
    </div>
</div>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Busqueda avanzada</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("SearchAv", "Usuario", FormMethod.Post))
                {
                    @:<input type="text" name="busqueda" class="form-control" placeholder="Escribe tu busqueda">
                    Html.RenderAction("CategoriaList", "Categoria");
                    @:<input type="submit" />
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

dominiolifetagGen/TagLifeASPMVC/Views/Usuario/SubirContenido.cshtml
﻿@model TagLifeASPMVC.Models.Usuario

@{
    ViewBag.Title = "SubirContenido";
    Layout = "~/Views/Shared/_LayoutUSER.cshtml";
}

<br />
<br />
<div class="row">
    <div class="col-xs-12 text-center">
        <h3>&nbsp;Sube tu contenido:</h3>
    </div>
</div>
@using (Html.BeginForm("Subircontenido", "Usuario", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2 well well-lg">
            <div class="form-group col-xs-5 col-xs-offset-1">
                <label for="nombre">Nombre de publicación:</label>
                <input type="text" placeholder="Nombre" id="nombre" name="nombre">
                <label for="archivo">Introduce la ruta HTTP del fichero:</label>
                <input type="text" placeholder="Fichero" id="archivo" name="archivo">
            </div>
            <br />
            <div class="form-group col-xs-3 col-xs-offset-2">
                <button type="button" class="btn btn-success btn-block" data-toggle="modal" data-target="#myModal1">Agregar Categorias</button><br />
                <button type="button" class="btn btn-success btn-block" data-toggle="modal" data-target="#myModal2">Agregar Etiquetas</button>
            </div>
            <div class="form-group col-xs-10 col-xs-offset-1">
                <b>Tipo de archivo:</b><br />
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="tipo" id="Imagen" value="Imagen">
                    <label class="form-check-label" for="Imagen">Imagen</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="tipo" id="Audio" value="Audio">
                    <label class="form-check-label" for="Audio">Audio</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="tipo" id="Video" value="Video">
                    <label class="form-check-label" for="Video">Video</label>
                </div>
            </div>
            <div class="form-group col-xs-10 col-xs-offset-1">
                <button type="submit" class="btn btn-success" style="float:right;">Subir</button>
            </div>
        </div>
    </div>
    <div id="myModal1" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Selecciona una o mas categorias:</h4>
                </div>
                <div class="modal-body">
                    @{Html.RenderAction("CargarCategorias", "Categoria");}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
    </div>
    <div id="myModal2" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Agrega las etiquetas:</h4>
                </div>
                <div class="modal-body">
                    <label for="etiquetas">Introduzca la/s etiqueta/s que desea asignar (separadas por comas):</label>
                    <input type="text" class="form-control" id="etiquetas" name="etiquetas" placeholder="Escribe aquí las etiquetas"><br />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
    </div>
                        }

dominiolifetagGen/TagLifeASPMVC/Views/Usuario/favoritos.cshtml
@model TagLifeASPMVC.Models.Usuario

@{
    ViewBag.Title = "LifeTag | Favoritos";
	Layout = "~/Views/Shared/_LayoutUSER.cshtml";
}
  <br/>
    @if (ViewBag.Men == "usuario incorrecto")
    {
        @:<div class="container">
            @:<h2>Error</h2>
            @:<div class="alert alert-danger">
                @:<strong>Error de usuario:</strong> Los datos que ha introducido no son correctos
            @:</div>
        @:</div>
    }

    <br/>
    <br/>
    <div class="row">
        <div class="col-xs-12 text-center">
            <img src="https://image.flaticon.com/icons/png/128/54/54806.png" class="img-responsive" style="margin:0 auto;">
            <h3>&nbsp;Mi Lista de 'Me gustas'</h3>
        </div>
    </div>
    @{Html.RenderAction("CargarMeGusta", "Publicacion");}
    <!--en lugar de cargar las ultimas se cargan las publicaciones que le gustan a este perfil concretamente-->